version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:////app/app.db
      - OPENVERSE_URL=https://api.openverse.engineering
      - SECRET_KEY=dev-secret-key
    volumes:
      - ./backend:/app
    command: flask run --host=0.0.0.0 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  # SQLite is used for development, so we don't need PostgreSQL